TRAIN_CFG_MATURE = {
    "max_episode_length": 5000,
    "num_steps_per_env": 24,
    "save_interval": 200,
    "max_iterations": 10000,
    "num_envs": 64,
    "seed": 42,
    "multi_gpu": None,
    "experiment_name": "g1_amp_walk_forward_mature",
    "logger": "tensorboard",
    "empirical_normalization": True,

    "algorithm": {
        "class_name": "AMPPPO",
        "rnd_cfg": None,
        "symmetry_cfg": None,
        "num_learning_epochs": 5,
        "num_mini_batches": 4,
        "clip_param": 0.2,
        "gamma": 0.99,
        "lam": 0.95,
        "value_loss_coef": 1.0,
        "entropy_coef": 0.005,
        "learning_rate": 3e-4,
        "max_grad_norm": 1.0,
        "use_clipped_value_loss": True,
        "schedule": "adaptive",
        "desired_kl": 0.02,
        "normalize_advantage_per_mini_batch": False,
        "optimizer": "adam",
    },

    "policy": {
        "class_name": "ActorCritic",
        "actor_hidden_dims": (512, 256, 128),
        "critic_hidden_dims": (512, 256, 128),
        "activation": "elu",
        "init_noise_std": 1.0,
        "noise_std_type": "scalar",
    },

    "amp_motion_files": "data/motions_walk_forward",
    "amp_body_names": [
        "pelvis",
        "left_hip_roll_link",
        "left_knee_link",
        "left_ankle_roll_link",
        "right_hip_roll_link",
        "right_knee_link",
        "right_ankle_roll_link",
        "left_shoulder_roll_link",
        "left_elbow_link",
        "left_wrist_yaw_link",
        "right_shoulder_roll_link",
        "right_elbow_link",
        "right_wrist_yaw_link",
    ],
    "amp_anchor_name": "torso_link",
    "amp_reward_coef": 0.2,
    "amp_task_reward_lerp": 0.65,
    "amp_discr_hidden_dims": [1024, 512, 256],
    "min_normalized_std": [0.05] * 29,
    "amp_num_preload_transitions": 200000,
}
